#!/usr/bin/env python3
"""
llm_generate.py — FINAL VERSION

Pipeline:
  1) Build LLM prompt (README + prompt.txt + demo examples)
  2) Call Gemini-Pro via OpenAI-compatible API to generate traffic_profile (JSON)
  3) Parse & repair JSON
  4) Expand with simulator (simulate_trace_from_profile)
  5) Validate JSON trace
  6) Convert to PCAP
  7) Evaluate vs baseline PCAP
  8) Save results
"""

import os
import sys
import json
import re
from pathlib import Path
from datetime import datetime
from typing import Any, List, Dict

from openai import OpenAI
from validator.validator import validate_trace_file
from evaluator.eval import evaluate_pcap
from utils.json_to_pcap import json_to_pcap
from utils.traffic_simulator import simulate_trace_from_profile


# ----------------- CONSTANT PATHS ----------------- #

ROOT = Path(__file__).resolve().parent
GENERATED = ROOT / "generated"
RESULTS = ROOT / "results"
BASELINE = ROOT / "baseline"
EVAL_PCAP = ROOT / "evaluator" / "pcap"

# 目标总包数：配合 90–120 flows，期望 avg_pkts_per_flow ~ 40–70 左右
TARGET_TOTAL_PACKETS = 5000


# ----------------- HELPERS ----------------- #

def _read(path: Path) -> str:
    if path.exists():
        return path.read_text(encoding="utf-8")
    return ""


def _collect_demo_examples(max_files: int = 1) -> str:
    """Collect demo packet-level JSON samples for context only."""
    txt = []
    dirs = [BASELINE / "demo", BASELINE]
    count = 0

    for d in dirs:
        if not d.is_dir():
            continue
        for f in sorted(d.glob("*.json")):
            if count >= max_files:
                break
            try:
                content = f.read_text(encoding="utf-8")
                txt.append(f"// Example packet trace from {f.relative_to(ROOT)}:\n{content}")
                count += 1
            except:
                continue
    if not txt:
        return ""
    return (
        "\n\n### Reference Packet-Level Examples\n"
        "These examples show low-level packet traces generated BY THE SIMULATOR.\n"
        "You MUST NOT generate packets yourself. You produce ONLY a high-level profile.\n\n"
        + "\n\n".join(txt)
    )


def build_llm_prompt() -> str:
    readme = _read(ROOT / "README.md")
    base_prompt = _read(ROOT / "prompt.txt")
    demos = _collect_demo_examples()

    parts = []
    if readme:
        parts.append("## Project README\n" + readme)
    if base_prompt:
        parts.append("\n\n## Profile Prompt Instructions\n" + base_prompt)
    if demos:
        parts.append("\n\n" + demos)

    final = (
        "\n\n".join(parts)
        + "\n\n### Task\n"
        "Produce ONLY a JSON object for the traffic_profile.\n"
        "NO markdown, NO comments, NO explanation.\n"
    )
    return final


# ----------------- LLM ----------------- #

LLM_MODEL = os.getenv("LLM_MODEL", "gemini-2.5-pro")
LLM_BASE_URL = os.getenv(
    "LLM_BASE_URL",
    "https://generativelanguage.googleapis.com/v1beta/openai"
)

client = OpenAI(
    api_key=os.environ.get("OPENAI_API_KEY"),
    base_url=LLM_BASE_URL,
)


def call_llm(prompt: str) -> str:
    resp = client.chat.completions.create(
        model=LLM_MODEL,
        messages=[
            {
                "role": "system",
                "content": (
                    "You output ONLY a valid JSON object representing the traffic_profile.\n"
                    "NO text outside JSON. NO markdown. NO commentary.\n"
                ),
            },
            {"role": "user", "content": prompt},
        ],
        temperature=0.3,
        max_tokens=40000,
        response_format={"type": "json_object"},
    )
    msg = resp.choices[0].message.content
    if not msg:
        raise RuntimeError("LLM returned empty content.")
    return msg


# ----------------- JSON REPAIR ----------------- #

def extract_json(text: str) -> str:
    s = text.strip()

    # remove code fences if any
    if s.startswith("```"):
        s = re.sub(r"^```[^\n]*\n", "", s)
        s = re.sub(r"```$", "", s).strip()

    start = s.find("{")
    end = s.rfind("}")
    if start == -1 or end == -1 or end <= start:
        raise ValueError("Cannot locate JSON object in LLM output.")
    return s[start:end + 1]


def cleanup_json(text: str) -> str:
    """Fix trailing commas before } or ]."""
    s = text.strip()
    s = re.sub(r",\s*(?=[}\]])", "", s)
    return s


# ----------------- File Helpers ----------------- #

def pick_reference_pcap() -> str | None:
    if EVAL_PCAP.is_dir():
        for p in sorted(EVAL_PCAP.glob("*.pcap")):
            return str(p)
    return None


def pick_baseline_pcap() -> str:
    sample = BASELINE / "sample.pcap"
    if sample.exists():
        return str(sample)
    for p in sorted(BASELINE.glob("*.pcap")):
        return str(p)
    raise FileNotFoundError("No baseline PCAP found in baseline/.")


# ----------------- MAIN PIPELINE ----------------- #

def main():
    GENERATED.mkdir(exist_ok=True)
    RESULTS.mkdir(exist_ok=True)

    print("[info] ===== Building LLM prompt =====")
    prompt = build_llm_prompt()

    print("[info] ===== Calling LLM =====")
    try:
        raw = call_llm(prompt)
    except Exception as e:
        print(f"[fatal] LLM call failed: {e}")
        sys.exit(1)

    print("[info] Parsing traffic_profile JSON...")
    try:
        jraw = extract_json(raw)
        try:
            profile = json.loads(jraw)
        except:
            profile = json.loads(cleanup_json(jraw))
    except Exception as e:
        print(f"[fatal] Failed to parse JSON: {e}")
        print(f"[debug head]: {raw[:150]}")
        sys.exit(1)

    print("[info] Expanding via simulator...")
    try:
        packets = simulate_trace_from_profile(
            profile,
            target_total_packets=TARGET_TOTAL_PACKETS,
        )
    except Exception as e:
        print(f"[fatal] Simulator error: {e}")
        sys.exit(1)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    json_path = GENERATED / f"trace_{timestamp}.json"

    print(f"[info] Saving packet JSON to {json_path}")
    json_path.write_text(json.dumps(packets, indent=2), encoding="utf-8")

    print("[info] Validating JSON trace...")
    errors = validate_trace_file(str(json_path))
    if errors:
        print("[fatal] Validation FAILED:")
        for e in errors:
            print(" -", e)
        sys.exit(1)
    print("[info] Validation PASSED.")

    print("[info] Converting JSON → PCAP")
    pcap_path = GENERATED / f"trace_{timestamp}.pcap"
    ref_pcap = pick_reference_pcap()
    try:
        json_to_pcap(str(json_path), str(pcap_path), reference_pcap=ref_pcap)
    except:
        json_to_pcap(str(json_path), str(pcap_path))

    print("[info] Evaluating...")
    baseline_pcap = pick_baseline_pcap()
    metrics = evaluate_pcap(str(pcap_path), baseline_pcap)

    result_path = RESULTS / f"eval_{timestamp}.json"
    result_path.write_text(json.dumps(metrics, indent=2), encoding="utf-8")
    print(f"[info] Evaluation results written to {result_path}")

    print("[done] Pipeline complete.")


if __name__ == "__main__":
    main()
